### ISSUE TITLE
Before opening a new issue, please take a look at this

### ISSUE THREAD

**Issue by flaming-cl** [flaming-cl/editorjs-text-color-plugin#23]
Hi, if you are encountering some issues with this plugin, please take a look at this template and add it in your issue.
This helps us to better understand your issue, thanks.

### Editorjs Version
2.25

### Other unofficial Editorjs plugins you are using
If not, leave this blank

### Device
PC

### Operating System
Ubuntu / Windows / Mac

### Browser
Chrome 114?

### Expected outcome

**Comment by fyrye** [comment]
You can update the Bug Report template under https://github.com/natterstefan/editorjs-inline-tool/blob/master/.github/ISSUE_TEMPLATE/bug_report.md to include the desired headings and even [convert it to a form using YAML](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) to add input elements with validation rules.

```yaml
# .github/ISSUE_TEMPLATE/1_Bug_report.yaml

name: Bug Report
description: File a bug report
labels: Bug
title: "[Bug]: "
body:
    - type: input
      id: affected-version
      attributes:
         label: ColorPlugin Version
         description: Which version of ColorPlugin was used?
         placeholder: 
      validators:
          required: true
    - type: input
      id: editorjs-version
      attributes:
         label: EditorJS Version
         description: Which version of EditorJS was used?
         placeholder: x.y.z
      validators:
          required: true
    - type: textarea
      id: reproduce
      attributes:
         label: How to reproduce the issue
         description: Minimal example of how you encountered the issue
      validators:
          required: true

# ...
```
